
name: Search vacant tennis-coat
on: 
  workflow_dispatch:
    branches:
      - master
  schedule: #execute every 6min.
    - cron: '*/6 * * * *' 
  #push:


jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v2
      - name: SSH setting for access private submodule
        env:
          TOKEN: ${{ secrets.PRIVATE_TOKEN }} #RSA key (not OPENSSH)
        run: |
          mkdir -p /home/runner/.ssh/
          echo -e "$TOKEN" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      - name: Checkout submodules
        shell: bash
        run: git submodule update --init --force --recursive

      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install lib
        run: |
          python3 -m pip install selenium
          python3 -m pip install webdriver-manager
          python3 -m pip install chromedriver-binary
          python3 -m pip install requests
          python3 -m pip install selenium

      - name: search vacant tennis-coat
        run: python3 src/tokyo_tenniscoat_act.py    
